name: Deploy ReasonReact to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Opam & Deps
      #   run: |
      #     sudo apt-get install opam -y
      #     opam init 
      #     opam install . --deps-only -y

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: Node Deps
        run: |
          npm install -y

      - name: Build ReasonReact app
        run: |
          # eval $(opam env)
          # npm run build

          mkdir -p dist/_build/default/output
          cp _build/default/output dist/_build/default/output -fr
          cp index.html dist/
          # cp styles.css dist/

      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: melange
      #     directory: ./dist
      #     branch: main
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: dist
